server:
  port: ${PORT:8080}
spring:
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always  # o embedded
      data-locations: classpath:data.sql
vaadin:
  launch-browser: true
  allowed-packages:
    - "com.vaadin"
    - "org.vaadin"
    - "com.flowingcode"
    - "com.uah.tfm.zakado.zkd"


logging:
  level:
    org:
      atmosphere: warn