server:
  port: 8081
spring:
  jpa:
    defer-datasource-initialization: true
  #sql:
  #  init:
  #    mode: embedded  # o always
  #    data-locations: classpath:data.sql
  mustache:
    check-template-location: false
vaadin:
  launch-browser: true
  allowed-packages:
    - "com.vaadin"
    - "org.vaadin"
    - "dev.hilla"
    - "com.uah.tfm.zakado.zkd"


logging:
  level:
    org:
      atmosphere: warn
